name: Ruff
on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: check --ignore E741,F841
          src: ./cea
